version: "3.3"

services:
  app:
    image: ovvesley/minicurso-deploy:latest
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    
      
networks:
  default:
    driver: bridge
